FROM golang:1.22.5-alpine3.20 as build

WORKDIR /app

COPY . .
RUN go mod download
RUN go build -o Bot github.com/zixrend/golang-tg-bot/cmd

FROM alpine:3.20 as run

WORKDIR /app

COPY --from=build /app/Bot .

EXPOSE 8000
ENTRYPOINT ./Bot