FROM golang:1.22.5-alpine3.20 AS build

WORKDIR /app
RUN go install github.com/pressly/goose/v3/cmd/goose@latest
COPY . .

RUN go mod download
RUN go build -o Bot github.com/zixrend/golang-tg-bot/cmd

FROM alpine:3.20
WORKDIR /app

COPY --from=build /app/Bot .
COPY --from=build /go/bin/goose /usr/local/bin/goose
COPY ./sql ./sql

EXPOSE 8000
ENTRYPOINT sh -c 'goose -dir ./sql postgres "host=$DB_HOST port=$DB_PORT user=$DB_USER dbname=$DB_NAME password=$DB_PASSWORD sslmode=disable" up && ./Bot'