#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
    CREATE DATABASE ${UPTRACE_DB};
    CREATE USER ${UPTRACE_USER} WITH PASSWORD '${UPTRACE_PASSWORD}';
    GRANT ALL PRIVILEGES ON DATABASE ${UPTRACE_DB} TO ${UPTRACE_USER};

    \c ${UPTRACE_DB}
    GRANT ALL ON SCHEMA public TO ${UPTRACE_USER};
    GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO ${UPTRACE_USER};
    GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO ${UPTRACE_USER};

    ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON TABLES TO ${UPTRACE_USER};
    ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON SEQUENCES TO ${UPTRACE_USER};
EOSQL
