// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: action.sql

package querier

import (
	"context"
)

const getRandomActionFromNewest = `-- name: GetRandomActionFromNewest :one
SELECT id, action
FROM (
    SELECT id, action
    FROM actions
    WHERE is_yourself = $1
    ORDER BY created_at DESC
    LIMIT 1000
) AS newest
ORDER BY RANDOM()
LIMIT 1
`

type GetRandomActionFromNewestRow struct {
	ID     int64
	Action string
}

func (q *Queries) GetRandomActionFromNewest(ctx context.Context, isYourself bool) (GetRandomActionFromNewestRow, error) {
	row := q.db.QueryRow(ctx, getRandomActionFromNewest, isYourself)
	var i GetRandomActionFromNewestRow
	err := row.Scan(&i.ID, &i.Action)
	return i, err
}

const insertNewAction = `-- name: InsertNewAction :exec
INSERT INTO actions (is_yourself, chat_tg_id, user_tg_id, action)
VALUES ($1, $2, $3, $4)
`

type InsertNewActionParams struct {
	IsYourself bool
	ChatTgID   int64
	UserTgID   int64
	Action     string
}

func (q *Queries) InsertNewAction(ctx context.Context, arg InsertNewActionParams) error {
	_, err := q.db.Exec(ctx, insertNewAction,
		arg.IsYourself,
		arg.ChatTgID,
		arg.UserTgID,
		arg.Action,
	)
	return err
}

const updateLastMessageAt = `-- name: UpdateLastMessageAt :exec
UPDATE chat_users
SET last_message_at = NOW()
WHERE chat_tg_id = $1
  AND user_tg_id = $2
`

type UpdateLastMessageAtParams struct {
	ChatTgID int64
	UserTgID int64
}

func (q *Queries) UpdateLastMessageAt(ctx context.Context, arg UpdateLastMessageAtParams) error {
	_, err := q.db.Exec(ctx, updateLastMessageAt, arg.ChatTgID, arg.UserTgID)
	return err
}
