// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: action.sql

package querier

import (
	"context"
)

const getRandomActionForStrangerFromNewest = `-- name: GetRandomActionForStrangerFromNewest :one
SELECT id, action
FROM (
    SELECT id, action
    FROM actions
    WHERE is_yourself = false
    ORDER BY created_at DESC
    LIMIT 1000
) AS newest
ORDER BY RANDOM()
LIMIT 1
`

type GetRandomActionForStrangerFromNewestRow struct {
	ID     int64
	Action string
}

func (q *Queries) GetRandomActionForStrangerFromNewest(ctx context.Context) (GetRandomActionForStrangerFromNewestRow, error) {
	row := q.db.QueryRow(ctx, getRandomActionForStrangerFromNewest)
	var i GetRandomActionForStrangerFromNewestRow
	err := row.Scan(&i.ID, &i.Action)
	return i, err
}

const getYourselfRandomActionFromNewest = `-- name: GetYourselfRandomActionFromNewest :one
SELECT id, action
FROM (
         SELECT id, action
         FROM actions
         WHERE is_yourself
         ORDER BY created_at DESC
         LIMIT 1000
     ) AS newest
ORDER BY RANDOM()
LIMIT 1
`

type GetYourselfRandomActionFromNewestRow struct {
	ID     int64
	Action string
}

func (q *Queries) GetYourselfRandomActionFromNewest(ctx context.Context) (GetYourselfRandomActionFromNewestRow, error) {
	row := q.db.QueryRow(ctx, getYourselfRandomActionFromNewest)
	var i GetYourselfRandomActionFromNewestRow
	err := row.Scan(&i.ID, &i.Action)
	return i, err
}

const updateLastMessageAt = `-- name: UpdateLastMessageAt :exec
UPDATE chat_users
SET last_message_at = NOW()
WHERE chat_tg_id = $1
  AND user_tg_id = $2
`

type UpdateLastMessageAtParams struct {
	ChatTgID int64
	UserTgID int64
}

func (q *Queries) UpdateLastMessageAt(ctx context.Context, arg UpdateLastMessageAtParams) error {
	_, err := q.db.Exec(ctx, updateLastMessageAt, arg.ChatTgID, arg.UserTgID)
	return err
}
