// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: chats.sql

package querier

import (
	"context"
)

const getChatCountForBroadcast = `-- name: GetChatCountForBroadcast :one
SELECT COUNT(*)
FROM chats
WHERE (type = 'supergroup' OR type = 'private' OR type = 'group')
AND is_active
`

func (q *Queries) GetChatCountForBroadcast(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, getChatCountForBroadcast)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getChatsForBroadcastCursorBased = `-- name: GetChatsForBroadcastCursorBased :many
SELECT
    c.id,
    c.tg_id
FROM chats c
WHERE (type = 'supergroup' OR type = 'private' OR type = 'group')
  AND is_active = true
  AND id > $1::bigint
ORDER BY id
LIMIT $2::int
`

type GetChatsForBroadcastCursorBasedParams struct {
	CursorID int64
	PageSize int32
}

type GetChatsForBroadcastCursorBasedRow struct {
	ID   int64
	TgID int64
}

func (q *Queries) GetChatsForBroadcastCursorBased(ctx context.Context, arg GetChatsForBroadcastCursorBasedParams) ([]GetChatsForBroadcastCursorBasedRow, error) {
	rows, err := q.db.Query(ctx, getChatsForBroadcastCursorBased, arg.CursorID, arg.PageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetChatsForBroadcastCursorBasedRow{}
	for rows.Next() {
		var i GetChatsForBroadcastCursorBasedRow
		if err := rows.Scan(&i.ID, &i.TgID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateChatStatusToDead = `-- name: UpdateChatStatusToDead :exec
UPDATE chats
SET
    is_active = false
WHERE tg_id = ANY($1::bigint[])
`

func (q *Queries) UpdateChatStatusToDead(ctx context.Context, deadIds []int64) error {
	_, err := q.db.Exec(ctx, updateChatStatusToDead, deadIds)
	return err
}

const updateLastSysTimestamp = `-- name: UpdateLastSysTimestamp :exec
UPDATE chats
SET
    last_sys_message_at = now()
WHERE tg_id = ANY($1::bigint[])
`

func (q *Queries) UpdateLastSysTimestamp(ctx context.Context, aliveChats []int64) error {
	_, err := q.db.Exec(ctx, updateLastSysTimestamp, aliveChats)
	return err
}
