// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: d_action.sql

package querier

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
	decimal "github.com/shopspring/decimal"
)

const getLastTimeDAction = `-- name: GetLastTimeDAction :one
SELECT cu.last_grow_at
FROM chat_users cu
WHERE chat_tg_id = $1 AND user_tg_id = $2
`

type GetLastTimeDActionParams struct {
	ChatTgID int64
	UserTgID int64
}

func (q *Queries) GetLastTimeDAction(ctx context.Context, arg GetLastTimeDActionParams) (*time.Time, error) {
	row := q.db.QueryRow(ctx, getLastTimeDAction, arg.ChatTgID, arg.UserTgID)
	var last_grow_at *time.Time
	err := row.Scan(&last_grow_at)
	return last_grow_at, err
}

const growD = `-- name: GrowD :one
UPDATE chat_users
SET
    d_length = GREATEST(d_length + $1, 0),
    last_grow_at = now()
WHERE chat_tg_id = $2
  AND user_tg_id = $3
  AND (last_grow_at IS NULL OR last_grow_at < NOW() - $4::interval)
RETURNING d_length
`

type GrowDParams struct {
	DLength  decimal.Decimal
	ChatTgID int64
	UserTgID int64
	Cooldown pgtype.Interval
}

func (q *Queries) GrowD(ctx context.Context, arg GrowDParams) (decimal.Decimal, error) {
	row := q.db.QueryRow(ctx, growD,
		arg.DLength,
		arg.ChatTgID,
		arg.UserTgID,
		arg.Cooldown,
	)
	var d_length decimal.Decimal
	err := row.Scan(&d_length)
	return d_length, err
}
