// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: f_action.sql

package querier

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const confirmFAction = `-- name: ConfirmFAction :exec
UPDATE chat_users
SET
    f_action_from_stranger_count = f_action_from_stranger_count + 1
WHERE chat_tg_id = $1
  AND user_tg_id = $2
`

type ConfirmFActionParams struct {
	ChatTgID int64
	UserTgID int64
}

func (q *Queries) ConfirmFAction(ctx context.Context, arg ConfirmFActionParams) error {
	_, err := q.db.Exec(ctx, confirmFAction, arg.ChatTgID, arg.UserTgID)
	return err
}

const getLastTimeFAction = `-- name: GetLastTimeFAction :one
SELECT cu.last_s_at
FROM chat_users cu
WHERE chat_tg_id = $1 AND user_tg_id = $2
`

type GetLastTimeFActionParams struct {
	ChatTgID int64
	UserTgID int64
}

func (q *Queries) GetLastTimeFAction(ctx context.Context, arg GetLastTimeFActionParams) (*time.Time, error) {
	row := q.db.QueryRow(ctx, getLastTimeFAction, arg.ChatTgID, arg.UserTgID)
	var last_s_at *time.Time
	err := row.Scan(&last_s_at)
	return last_s_at, err
}

const tryPerformFAction = `-- name: TryPerformFAction :one
UPDATE chat_users
SET
    f_action_count = f_action_count + 1,
    last_s_at = now()
WHERE chat_tg_id = $1
  AND user_tg_id = $2
  AND (last_s_at IS NULL OR last_s_at < NOW() - $3::interval)
RETURNING f_action_count
`

type TryPerformFActionParams struct {
	ChatTgID int64
	UserTgID int64
	Cooldown pgtype.Interval
}

func (q *Queries) TryPerformFAction(ctx context.Context, arg TryPerformFActionParams) (int32, error) {
	row := q.db.QueryRow(ctx, tryPerformFAction, arg.ChatTgID, arg.UserTgID, arg.Cooldown)
	var f_action_count int32
	err := row.Scan(&f_action_count)
	return f_action_count, err
}
