// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: leaderboards.sql

package querier

import (
	"context"

	decimal "github.com/shopspring/decimal"
)

const getChatLeaderBoards = `-- name: GetChatLeaderBoards :many
WITH top AS (
    SELECT
        user_tg_id,
        d_length,
        m_action_count,
        f_action_count,
        f_action_from_stranger_count,
        s_action_count,
        s_action_from_stranger_count,
        loses
    FROM chat_users
    WHERE chat_tg_id = $1
    ORDER BY d_length DESC
    LIMIT 10
)
SELECT
    u.user_name,
    u.user_tag,
    top.user_tg_id, top.d_length, top.m_action_count, top.f_action_count, top.f_action_from_stranger_count, top.s_action_count, top.s_action_from_stranger_count, top.loses
FROM top
JOIN users u ON u.tg_id = top.user_tg_id
ORDER BY top.d_length DESC
`

type GetChatLeaderBoardsRow struct {
	UserName                 string
	UserTag                  *string
	UserTgID                 int64
	DLength                  decimal.Decimal
	MActionCount             int32
	FActionCount             int32
	FActionFromStrangerCount int32
	SActionCount             int32
	SActionFromStrangerCount int32
	Loses                    int32
}

func (q *Queries) GetChatLeaderBoards(ctx context.Context, chatTgID int64) ([]GetChatLeaderBoardsRow, error) {
	rows, err := q.db.Query(ctx, getChatLeaderBoards, chatTgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetChatLeaderBoardsRow{}
	for rows.Next() {
		var i GetChatLeaderBoardsRow
		if err := rows.Scan(
			&i.UserName,
			&i.UserTag,
			&i.UserTgID,
			&i.DLength,
			&i.MActionCount,
			&i.FActionCount,
			&i.FActionFromStrangerCount,
			&i.SActionCount,
			&i.SActionFromStrangerCount,
			&i.Loses,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getGlobalLeaderBoards = `-- name: GetGlobalLeaderBoards :many
SELECT
    u.user_name,
    u.tg_id,
    u.user_tag,
    cu.d_length, cu.m_action_count, cu.f_action_count, cu.f_action_from_stranger_count, cu.s_action_count, cu.s_action_from_stranger_count, cu.loses
FROM users u
CROSS JOIN LATERAL (
    SELECT
        d_length,
        m_action_count,
        f_action_count,
        f_action_from_stranger_count,
        s_action_count,
        s_action_from_stranger_count,
        loses
    FROM chat_users
    WHERE user_tg_id = u.tg_id
    ORDER BY d_length DESC
    LIMIT 1
    ) cu
ORDER BY cu.d_length DESC
LIMIT 10
`

type GetGlobalLeaderBoardsRow struct {
	UserName                 string
	TgID                     int64
	UserTag                  *string
	DLength                  decimal.Decimal
	MActionCount             int32
	FActionCount             int32
	FActionFromStrangerCount int32
	SActionCount             int32
	SActionFromStrangerCount int32
	Loses                    int32
}

func (q *Queries) GetGlobalLeaderBoards(ctx context.Context) ([]GetGlobalLeaderBoardsRow, error) {
	rows, err := q.db.Query(ctx, getGlobalLeaderBoards)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetGlobalLeaderBoardsRow{}
	for rows.Next() {
		var i GetGlobalLeaderBoardsRow
		if err := rows.Scan(
			&i.UserName,
			&i.TgID,
			&i.UserTag,
			&i.DLength,
			&i.MActionCount,
			&i.FActionCount,
			&i.FActionFromStrangerCount,
			&i.SActionCount,
			&i.SActionFromStrangerCount,
			&i.Loses,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
