// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: m_action.sql

package querier

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const getLastTimeMAction = `-- name: GetLastTimeMAction :one
SELECT cu.last_m_at
FROM chat_users cu
WHERE chat_tg_id = $1 AND user_tg_id = $2
`

type GetLastTimeMActionParams struct {
	ChatTgID int64
	UserTgID int64
}

func (q *Queries) GetLastTimeMAction(ctx context.Context, arg GetLastTimeMActionParams) (*time.Time, error) {
	row := q.db.QueryRow(ctx, getLastTimeMAction, arg.ChatTgID, arg.UserTgID)
	var last_m_at *time.Time
	err := row.Scan(&last_m_at)
	return last_m_at, err
}

const tryPerformMAction = `-- name: TryPerformMAction :one
UPDATE chat_users
SET
    m_action_count = m_action_count + 1,
    last_m_at = now()
WHERE chat_tg_id = $1
  AND user_tg_id = $2
  AND (last_m_at IS NULL OR last_m_at < NOW() - $3::interval)
RETURNING m_action_count
`

type TryPerformMActionParams struct {
	ChatTgID int64
	UserTgID int64
	Cooldown pgtype.Interval
}

func (q *Queries) TryPerformMAction(ctx context.Context, arg TryPerformMActionParams) (int32, error) {
	row := q.db.QueryRow(ctx, tryPerformMAction, arg.ChatTgID, arg.UserTgID, arg.Cooldown)
	var m_action_count int32
	err := row.Scan(&m_action_count)
	return m_action_count, err
}
