// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package querier

import (
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

type Action struct {
	ID         int64
	IsYourself bool
	ChatID     int64
	UserID     int64
	Action     string
	CreatedAt  time.Time
}

type Chat struct {
	ID               int64
	TgID             int64
	Type             string
	Name             string
	LastCGameAt      *time.Time
	LastSysMessageAt *time.Time
	LastMessageAt    time.Time
	IsActive         bool
	MemberCount      int32
	CreatedAt        time.Time
	UpdatedAt        time.Time
}

type ChatUser struct {
	UserTgID                 int64
	ChatTgID                 int64
	IsUserRemoved            bool
	LastMessageAt            time.Time
	MActionCount             int32
	LastMAt                  *time.Time
	DLength                  pgtype.Numeric
	LastGrowAt               *time.Time
	FActionCount             int32
	LastFAt                  *time.Time
	FActionFromStrangerCount int32
	SActionCount             int32
	LastSAt                  *time.Time
	SActionFromStrangerCount int32
	GamesPlayed              int32
	Loses                    int32
	CreatedAt                time.Time
}

type User struct {
	ID           int64
	TgID         int64
	UserTag      *string
	UserName     string
	UserLastname *string
	UserRole     string
	CreatedAt    time.Time
	UpdatedAt    time.Time
}
