// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package querier

import (
	"context"
	"time"

	decimal "github.com/shopspring/decimal"
)

type Querier interface {
	ConfirmFAction(ctx context.Context, arg ConfirmFActionParams) error
	ConfirmSAction(ctx context.Context, arg ConfirmSActionParams) error
	GetAllAdminTimeStats(ctx context.Context) (GetAllAdminTimeStatsRow, error)
	GetAllTimeStats(ctx context.Context) (GetAllTimeStatsRow, error)
	GetLastTimeDAction(ctx context.Context, arg GetLastTimeDActionParams) (*time.Time, error)
	GetLastTimeFAction(ctx context.Context, arg GetLastTimeFActionParams) (*time.Time, error)
	GetLastTimeMAction(ctx context.Context, arg GetLastTimeMActionParams) (*time.Time, error)
	GetLastTimeSAction(ctx context.Context, arg GetLastTimeSActionParams) (*time.Time, error)
	GetRandomActionFromNewest(ctx context.Context, isYourself bool) (GetRandomActionFromNewestRow, error)
	GetUserByTgId(ctx context.Context, tgID int64) (User, error)
	GetUserStatsByTgId(ctx context.Context, arg GetUserStatsByTgIdParams) (GetUserStatsByTgIdRow, error)
	GrowD(ctx context.Context, arg GrowDParams) (decimal.Decimal, error)
	InitChatUserData(ctx context.Context, arg InitChatUserDataParams) error
	InsertNewAction(ctx context.Context, arg InsertNewActionParams) error
	SetUserRoleByTgId(ctx context.Context, arg SetUserRoleByTgIdParams) error
	TryPerformFAction(ctx context.Context, arg TryPerformFActionParams) (int32, error)
	TryPerformMAction(ctx context.Context, arg TryPerformMActionParams) (int32, error)
	TryPerformSAction(ctx context.Context, arg TryPerformSActionParams) (int32, error)
	UpdateLastMessageAt(ctx context.Context, arg UpdateLastMessageAtParams) error
}

var _ Querier = (*Queries)(nil)
