// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package querier

import (
	"context"
	"time"

	decimal "github.com/shopspring/decimal"
)

type Querier interface {
	ConfirmFAction(ctx context.Context, arg ConfirmFActionParams) error
	ConfirmSAction(ctx context.Context, arg ConfirmSActionParams) error
	GetAllAdminTimeStats(ctx context.Context) (GetAllAdminTimeStatsRow, error)
	GetAllTimeStats(ctx context.Context) (GetAllTimeStatsRow, error)
	GetChatCountForBroadcast(ctx context.Context) (int64, error)
	GetChatLeaderBoards(ctx context.Context, chatTgID int64) ([]GetChatLeaderBoardsRow, error)
	GetChatMemberCount(ctx context.Context, chatTgID int64) (int64, error)
	GetChatsForBroadcastCursorBased(ctx context.Context, arg GetChatsForBroadcastCursorBasedParams) ([]GetChatsForBroadcastCursorBasedRow, error)
	GetGameLastTime(ctx context.Context, tgID int64) (*time.Time, error)
	GetGlobalLeaderBoards(ctx context.Context) ([]GetGlobalLeaderBoardsRow, error)
	GetLastTimeDAction(ctx context.Context, arg GetLastTimeDActionParams) (*time.Time, error)
	GetLastTimeFAction(ctx context.Context, arg GetLastTimeFActionParams) (*time.Time, error)
	GetLastTimeMAction(ctx context.Context, arg GetLastTimeMActionParams) (*time.Time, error)
	GetLastTimeSAction(ctx context.Context, arg GetLastTimeSActionParams) (*time.Time, error)
	GetRandomActionFromNewest(ctx context.Context, isYourself bool) (GetRandomActionFromNewestRow, error)
	GetUserByTgId(ctx context.Context, tgID int64) (User, error)
	GetUserStatsByTgId(ctx context.Context, arg GetUserStatsByTgIdParams) (GetUserStatsByTgIdRow, error)
	GetUsersForGameCursorBased(ctx context.Context, arg GetUsersForGameCursorBasedParams) ([]GetUsersForGameCursorBasedRow, error)
	GrowD(ctx context.Context, arg GrowDParams) (decimal.Decimal, error)
	InitChatUserData(ctx context.Context, arg InitChatUserDataParams) error
	InsertNewAction(ctx context.Context, arg InsertNewActionParams) error
	RecordGame(ctx context.Context, arg RecordGameParams) error
	RecordGameLose(ctx context.Context, arg RecordGameLoseParams) error
	RemoveLostUsers(ctx context.Context, arg RemoveLostUsersParams) error
	SetUserRoleByTgId(ctx context.Context, arg SetUserRoleByTgIdParams) error
	StartGame(ctx context.Context, arg StartGameParams) (*time.Time, error)
	TryPerformFAction(ctx context.Context, arg TryPerformFActionParams) (int32, error)
	TryPerformMAction(ctx context.Context, arg TryPerformMActionParams) (int32, error)
	TryPerformSAction(ctx context.Context, arg TryPerformSActionParams) (int32, error)
	UpdateChatStatusToDead(ctx context.Context, deadIds []int64) error
	UpdateLastMessageAt(ctx context.Context, arg UpdateLastMessageAtParams) error
	UpdateLastSysTimestamp(ctx context.Context, aliveChats []int64) error
}

var _ Querier = (*Queries)(nil)
