// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package querier

import (
	"context"
)

type Querier interface {
	GetUserByTgId(ctx context.Context, tgID int64) (User, error)
	InitChatUserData(ctx context.Context, arg InitChatUserDataParams) error
}

var _ Querier = (*Queries)(nil)
