// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: s_action.sql

package querier

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const confirmSAction = `-- name: ConfirmSAction :exec
UPDATE chat_users
SET
    s_action_count = s_action_count + 1
WHERE chat_tg_id = $1
  AND user_tg_id = $2
`

type ConfirmSActionParams struct {
	ChatTgID int64
	UserTgID int64
}

func (q *Queries) ConfirmSAction(ctx context.Context, arg ConfirmSActionParams) error {
	_, err := q.db.Exec(ctx, confirmSAction, arg.ChatTgID, arg.UserTgID)
	return err
}

const getLastTimeSAction = `-- name: GetLastTimeSAction :one
SELECT cu.last_s_at
FROM chat_users cu
WHERE chat_tg_id = $1 AND user_tg_id = $2
`

type GetLastTimeSActionParams struct {
	ChatTgID int64
	UserTgID int64
}

func (q *Queries) GetLastTimeSAction(ctx context.Context, arg GetLastTimeSActionParams) (*time.Time, error) {
	row := q.db.QueryRow(ctx, getLastTimeSAction, arg.ChatTgID, arg.UserTgID)
	var last_s_at *time.Time
	err := row.Scan(&last_s_at)
	return last_s_at, err
}

const tryPerformSAction = `-- name: TryPerformSAction :one
UPDATE chat_users
SET
    s_action_from_stranger_count = s_action_from_stranger_count + 1,
    last_s_at = now()
WHERE chat_tg_id = $1
  AND user_tg_id = $2
  AND (last_s_at IS NULL OR last_s_at < NOW() - $3::interval)
RETURNING s_action_from_stranger_count
`

type TryPerformSActionParams struct {
	ChatTgID int64
	UserTgID int64
	Cooldown pgtype.Interval
}

func (q *Queries) TryPerformSAction(ctx context.Context, arg TryPerformSActionParams) (int32, error) {
	row := q.db.QueryRow(ctx, tryPerformSAction, arg.ChatTgID, arg.UserTgID, arg.Cooldown)
	var s_action_from_stranger_count int32
	err := row.Scan(&s_action_from_stranger_count)
	return s_action_from_stranger_count, err
}
