// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package querier

import (
	"context"

	decimal "github.com/shopspring/decimal"
)

const getUserByTgId = `-- name: GetUserByTgId :one
SELECT id, tg_id, user_tag, user_name, user_lastname, user_role, created_at, updated_at
FROM users u
WHERE u.tg_id = $1
`

func (q *Queries) GetUserByTgId(ctx context.Context, tgID int64) (User, error) {
	row := q.db.QueryRow(ctx, getUserByTgId, tgID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.TgID,
		&i.UserTag,
		&i.UserName,
		&i.UserLastname,
		&i.UserRole,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserStatsByTgId = `-- name: GetUserStatsByTgId :one
SELECT
    u.user_name,
    c.name,
    cu.d_length,
    cu.m_action_count,
    cu.f_action_count,
    cu.s_action_count,
    cu.loses
FROM chat_users cu
JOIN chats c on cu.chat_tg_id = c.tg_id
JOIN users u on cu.user_tg_id = u.tg_id
WHERE cu.chat_tg_id = $1 AND cu.user_tg_id = $2
`

type GetUserStatsByTgIdParams struct {
	ChatTgID int64
	UserTgID int64
}

type GetUserStatsByTgIdRow struct {
	UserName     string
	Name         string
	DLength      decimal.Decimal
	MActionCount int32
	FActionCount int32
	SActionCount int32
	Loses        int32
}

func (q *Queries) GetUserStatsByTgId(ctx context.Context, arg GetUserStatsByTgIdParams) (GetUserStatsByTgIdRow, error) {
	row := q.db.QueryRow(ctx, getUserStatsByTgId, arg.ChatTgID, arg.UserTgID)
	var i GetUserStatsByTgIdRow
	err := row.Scan(
		&i.UserName,
		&i.Name,
		&i.DLength,
		&i.MActionCount,
		&i.FActionCount,
		&i.SActionCount,
		&i.Loses,
	)
	return i, err
}

const initChatUserData = `-- name: InitChatUserData :exec
SELECT init_chat_user_data($1, $2, $3, $4, $5, $6, $7, $8)
`

type InitChatUserDataParams struct {
	PUserTgID     int64
	PUserTag      string
	PUserName     string
	PUserLastname string
	PChatTgID     int64
	PChatType     string
	PChatName     string
	PMemberCount  int32
}

func (q *Queries) InitChatUserData(ctx context.Context, arg InitChatUserDataParams) error {
	_, err := q.db.Exec(ctx, initChatUserData,
		arg.PUserTgID,
		arg.PUserTag,
		arg.PUserName,
		arg.PUserLastname,
		arg.PChatTgID,
		arg.PChatType,
		arg.PChatName,
		arg.PMemberCount,
	)
	return err
}

const setUserRoleByTgId = `-- name: SetUserRoleByTgId :exec
UPDATE users u
SET user_role = $1
WHERE u.tg_id = $2
`

type SetUserRoleByTgIdParams struct {
	UserRole string
	TgID     int64
}

func (q *Queries) SetUserRoleByTgId(ctx context.Context, arg SetUserRoleByTgIdParams) error {
	_, err := q.db.Exec(ctx, setUserRoleByTgId, arg.UserRole, arg.TgID)
	return err
}
